export default [
  {
    name: "Bedroom",
    room: "Bedroom",
    price: "15000",
    color: "#D6FEBD",
  },
  {
    name: "Living Room",
    room: "Living Room",
    price: "15000",
    color: "#EAB8B8",
  },
  {
    name: "Kid's Bedroom",
    room: "Kid's Bedroom",
    price: "15000",
    color: "#CDF0FF",
  },
  {
    name: "Dinnig Room",
    room: "Dinnig Room",
    price: "15000",
    color: "#D1C2F9",
  },
  {
    name: "Single Bathroom",
    room: "Single Bathroom",
    price: "15000",
    color: "#D6FEBD",
  },
  {
    name: "Double Bathroom",
    room: "Double Bathroom",
    price: "15000",
    color: "#EAB8B8",
  },
  {
    name: "Bath/Closet",
    room: "Bath/Closet",
    price: "15000",
    color: "#CDF0FF",
  },
  {
    name: "Gym",
    room: "Gym",
    price: "15000",
    color: "#D1C2F9",
  },
  {
    name: "Music Room",
    room: "Music Room",
    price: "15000",
    color: "#D6FEBD",
  },
  {
    name: "Office",
    room: "Office",
    price: "15000",
    color: "#EAB8B8",
  },
  {
    name: "Workshop",
    room: "Workshop",
    price: "15000",
    color: "#CDF0FF",
  },
  {
    name: "Theartre",
    room: "Theartre",
    price: "15000",
    color: "#D1C2F9",
  },
  {
    name: "Storage",
    room: "Storage",
    price: "15000",
    color: "#D6FEBD",
  },
  {
    name: "Game Room",
    room: "Game Room",
    price: "15000",
    color: "#EAB8B8",
  },
  {
    name: "Empty",
    room: "Empty",
    price: "15000",
    color: "#CDF0FF",
  },
];
