export default [
  {
    name: "Bedroom",
    room: "Bedroom",
    price: "15000",
    color: "#CC0033",
  },
  {
    name: "Living Room",
    room: "Living Room",
    price: "15000",
    color: "#FFCC00",
  },
  {
    name: "Kid's Bedroom",
    room: "Kid's Bedroom",
    price: "15000",
    color: "#00194B",
  },
  {
    name: "Dinnig Room",
    room: "Dinnig Room",
    price: "15000",
    color: "#D1C2F9",
  },
  {
    name: "Single Bathroom",
    room: "Single Bathroom",
    price: "15000",
    color: "#0052ff",
  },
  {
    name: "Double Bathroom",
    room: "Double Bathroom",
    price: "15000",
    color: "#FFCCCC",
  },
  {
    name: "Bath/Closet",
    room: "Bath/Closet",
    price: "15000",
    color: "#CCFFE5",
  },
  {
    name: "Gym",
    room: "Gym",
    price: "15000",
    color: "#66FF66",
  },
  {
    name: "Music Room",
    room: "Music Room",
    price: "15000",
    color: "#CC9966",
  },
  {
    name: "Office",
    room: "Office",
    price: "15000",
    color: "#99CC99",
  },
  {
    name: "Workshop",
    room: "Workshop",
    price: "15000",
    color: "#00FFFF",
  },
  {
    name: "Theartre",
    room: "Theartre",
    price: "15000",
    color: "#00FF00",
  },
  {
    name: "Storage",
    room: "Storage",
    price: "15000",
    color: "#FF00FF",
  },
  {
    name: "Game Room",
    room: "Game Room",
    price: "15000",
    color: "#CC6699",
  },
  {
    name: "Empty",
    room: "Empty",
    price: "15000",
    color: "#0099CC",
  },
];
