export default [
  {
    name: "Bedroom",
    room: "Bedroom",
    price: "15000",
    color: "#6A5ACD",
  },
  {
    name: "Living Room",
    room: "Living Room",
    price: "15000",
    color: "#87CEFA",
  },
  {
    name: "Kid's Bedroom",
    room: "Kid's Bedroom",
    price: "15000",
    color: "#CDF0FF",
  },
  {
    name: "Dinnig Room",
    room: "Dinnig Room",
    price: "15000",
    color: "#D1C2F9",
  },
  {
    name: "Single Bathroom",
    room: "Single Bathroom",
    price: "15000",
    color: "#E3F705",
  },
  {
    name: "Double Bathroom",
    room: "Double Bathroom",
    price: "15000",
    color: "#FF69B4",
  },
  {
    name: "Bath/Closet",
    room: "Bath/Closet",
    price: "15000",
    color: "#00FFFF",
  },
  {
    name: "Gym",
    room: "Gym",
    price: "15000",
    color: "#FFD700",
  },
  {
    name: "Music Room",
    room: "Music Room",
    price: "15000",
    color: "#A0522D",
  },
  {
    name: "Office",
    room: "Office",
    price: "15000",
    color: "#FF6347",
  },
  {
    name: "Workshop",
    room: "Workshop",
    price: "15000",
    color: "#FF4500",
  },
  {
    name: "Theartre",
    room: "Theartre",
    price: "15000",
    color: "#800080",
  },
  {
    name: "Storage",
    room: "Storage",
    price: "15000",
    color: "#4682B4",
  },
  {
    name: "Game Room",
    room: "Game Room",
    price: "15000",
    color: "#20B2AA",
  },
  {
    name: "Empty",
    room: "Empty",
    price: "15000",
    color: "#9370DB",
  },
];
